import type { NotificationsResponseData } from '@/types/_notificationInterfaces'

const dummyNotificationsResponseData: NotificationsResponseData = {
  count: 123,
  next: '---whatever--',
  previous: '----whatever----',
  results: [
    {
      id: 0,
      user_id: 0,
      content: 'string',
      type: 'STUDY_JOIN',
      is_read: false,
      back_url_link: 'string',
      created_at: '',
      updated_at: '',
    },
    {
      id: 1,
      user_id: 0,
      content: 'string',
      type: 'STUDY_JOIN',
      is_read: false,
      back_url_link: 'string',
      created_at: '',
      updated_at: '',
    },
    {
      id: 2,
      user_id: 0,
      content: 'string',
      type: 'STUDY_JOIN',
      is_read: true,
      back_url_link: 'string',
      created_at: '',
      updated_at: '',
    },
    {
      id: 4,
      user_id: 0,
      content: 'string',
      type: 'STUDY_JOIN',
      is_read: true,
      back_url_link: 'string',
      created_at: '',
      updated_at: '',
    },
    {
      id: 5,
      user_id: 0,
      content: 'string',
      type: 'STUDY_JOIN',
      is_read: true,
      back_url_link: 'string',
      created_at: '',
      updated_at: '',
    },
    {
      id: 6,
      user_id: 0,
      content: 'string',
      type: 'STUDY_JOIN',
      is_read: true,
      back_url_link: 'string',
      created_at: '',
      updated_at: '',
    },
  ],
}

export default dummyNotificationsResponseData
