export * from './_defaultInterfaces.ts'
export * from './_commonInGeneralInterfaces.ts'
export * from './_pageInterfaces.ts'
export * from './_tagApi.ts'
export * from './_lectureInterfaces.ts'
export * from './_interfaceRecruit.ts'
